-- TABLE USERS
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(32) NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at DATE NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sex INT NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_day INT NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_month INT NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_year INT NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS confirm_token VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at DATE DEFAULT CURRENT_DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at DATE DEFAULT CURRENT_DATE;

-- TABLE RESET PASSWORD

CREATE TABLE IF NOT EXISTS password_resets (
    id SERIAL PRIMARY KEY
);

ALTER TABLE password_resets ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL;
ALTER TABLE password_resets ADD COLUMN IF NOT EXISTS token VARCHAR(255) NOT NULL;
ALTER TABLE password_resets ADD COLUMN IF NOT EXISTS created_at DATE DEFAULT CURRENT_DATE;